spring:
  application:
    name: test-service
  datasource:
    url: jdbc:mysql://localhost:3306/sp?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

server:
  port: 8008

